### ISSUE TITLE
Enable caching for container build CI/CD

### ISSUE THREAD

**Issue by obriencj** [obriencj/pelican-inelegant#15]
Right now we rebuild every step of the container every time a pertinent change is committed. It would be better if we were to enable caching, so that unchanged steps could have their layers reused.

We would need to swap out `redhat-actions/buildah-build` for `docker/build-push-action` to take advantage of layer caching. Unfortunately this isn't part of the buildah action feature set currently.

Relevant blog on how to set up caching
https://depot.dev/blog/docker-layer-caching-in-github-actions

Current setup
```
      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true
          build-args: |
            GIT_COMMIT="${{ github.sha }}"
          containerfiles: |
            Containerfile
```

Open buildah-build question about same
https://github.com/redhat-actions/buildah-build/issues/90
